allowBuilds:
  electron-winstaller: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - app-builder-lib@26.15.2
  - dmg-builder@26.15.2
  - electron-builder-squirrel-windows@26.15.2
  - electron-builder@26.15.2

overrides:
  form-data: "^4.0.6"
  fast-uri: "^3.1.3"
  tar: "^7.5.18"
  brace-expansion: "^2.1.2"
  js-yaml: "^4.3.0"
